### ISSUE TITLE
working on other display version

### ISSUE THREAD

**Issue by ciocan** [samsonmking/epaper.js#1]
What needs to be changed to work on **880×528, 7.5inch E-Ink raw display, red / black / white three-color**?

**Comment by samsonmking** [comment]
>```
> const ws = new WebSocket("ws://localhost:8080");
>```
Good catch, I should change this in the examples.

**Comment by samsonmking** [comment]
I've created separate issues so we can individually track the status for each new display that's added. Closing this issue for now, and let's continue these discussions in #2 and #3.
