### ISSUE TITLE
Question: How to display images from file?

### ISSUE THREAD

**Issue by RaedsLab** [samsonmking/epaper.js#12]
Not exactly in the scope of the project, but just a generic question.

I wanted to save the screenshot in a PNG file to use as a sort of "snapshot".

The problem I'm facing that when i load the files again they don't get displayed properly, so I think i'm messing up some buffer formatting here.

Any idea why this isn't working the same as the PNG image here : https://github.com/samsonmking/epaper.js/blob/master/page.js#L11 ?

My understanding is that both functions (pupetter screenshot, and fs.readFile) should return a buffer 

```js 

const fs = require('fs')
const devices = require('./devices');
const { convertPNGto1BitBW } = require('./image.js');


(async () => {
    try {
        const device = devices.waveshare4in2
        const driver = device.driver

        driver.dev_init();
        driver.init();

        fs.readFile('./snapshot.png', async (err, buffer) => {
            if (err) {
                console.log("ERROR", err);
                driver.sleep();
                return;
            }
            const out = await convertPNGto1BitBW(buffer);
            driver.display(out)
            driver.sleep();
            console.log("Done")
        });

    } catch (e) {
        console.log("ERROR", e)
    }
})();

```

**Comment by samsonmking** [comment]
Hi @RaedsLab, if you look at the [puppeteer documentation here](https://github.com/puppeteer/puppeteer/blob/v5.3.0/docs/api.md#pagescreenshotoptions) it's possible to pass a path option into the `browserPage.screenshot` call on`page.js:11` to save the image to disk.

It should be possible to display any png image, as long as it is the exact same dimensions as the display. I noticed you're using the 4.2 inch display driver - are you still working on the 2.7" display?

**Comment by RaedsLab** [comment]
> it's possible to pass a path option into the browserPage.screenshot call onpage.js:11 to save the image to disk

@samsonmking That is exactly what I did.

I think the issue could be the low contrast of the image and not the file itself.

![image](https://user-images.githubusercontent.com/1442690/93083091-53371b80-f692-11ea-8faa-10c283fc12fb.png)

**Comment by samsonmking** [comment]
@RaedsLab could you try changing the background to black? That way you'd be able to easily tell if it's a contrast issue.You can also adjust the white / black threshold [here](https://github.com/samsonmking/epaper.js/blob/master/image.js#L21)

**Comment by RaedsLab** [comment]
It seems to be the issue, a good fix would be to add support to the 4Gray display mode https://github.com/samsonmking/epaper.js/blob/master/c/EPD_4in2.h#L128

**Comment by samsonmking** [comment]
@RaedsLab grayscale support is on the backlog! Glad you got it working - looking forward to the PR!
