### ISSUE TITLE
Add support for Waveshare 7in5bc black/red/white display

### ISSUE THREAD

**Issue by samsonmking** [samsonmking/epaper.js#2]
> @ciocan @RaedsLab if you have devices and would like to help with development or testing please let me know. 
Thank you @samsonmking 

I have tried to see if EPD_7in5 drivers will work on EPD_7in5bc which I have. It does not work.

The display method for EPD_7in5bc needs two buffer arguments. I managed to make it work like this:

```
Napi::Value Display(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    Napi::Buffer<uint8_t> jsBufferBlack = info[0].As<Napi::Buffer<uint8_t>>();
    Napi::Buffer<uint8_t> jsBufferRed = info[1].As<Napi::Buffer<uint8_t>>();
    EPD_7IN5BC_Display(reinterpret_cast<uint8_t *>(jsBufferBlack.Data()), reinterpret_cast<uint8_t *>(jsBufferRed.Data()));
    return env.Undefined();
}
```

It compiles ok, but now I need to figure out how to make the black and red buffers from the png image.

_Originally posted by @ciocan in https://github.com/samsonmking/epaper.js/issues/1#issuecomment-678699605_

**Comment by samsonmking** [comment]
Closing for now, will reopen if there is more interest in this display.

**Comment by csterritt** [comment]
Hi -- just ordered the "7.5inch E-Paper E-Ink Display HAT (B) For Raspberry Pi, 800×480 Pixels, Red / Black / White Three-Color, SPI Interface" from WaveShare [link](https://www.waveshare.com/7.5inch-e-paper-hat-b.htm). I don't see the magic "EPD" indicator anywhere, so I apologize if this is a different board.

But I'd love to have support for it, and am more than glad to help test! I'm willing to contribute code as well, but it may be faster for you to do it :-)

Thanks for doing this! Really looking forward to using it.
