### ISSUE TITLE
Add support for Waveshare 2in7 black/white display

### ISSUE THREAD

**Issue by samsonmking** [samsonmking/epaper.js#3]
Sounds like a fun project! I can start with testing for the 2.7" model next week. I'll be using a Raspberry PI model 3 B.

Haven't done much `C` coding in many years but i'll give it a shot!

_Originally posted by @RaedsLab in https://github.com/samsonmking/epaper.js/issues/1#issuecomment-678684313_

**Comment by RaedsLab** [comment]
I managed to get the weather project working on the 2in7 !! 🎉 

However, it seems that I got the width off. Do you know where I can get the correct values? 

This is what I used 
```
  waveshare2in7: {
    height: 264,
    width: 176,
    driver: waveshare2In7Driver,
  },
```

![IMG_20200826_165957](https://user-images.githubusercontent.com/1442690/91320404-c2b99980-e7bd-11ea-81f0-94048795c426.jpg)

I will open a PR as soon as the width issue is resolved

**Comment by samsonmking** [comment]
That's great progress!
> However, it seems that I got the width off. Do you know where I can get the correct values?

Could you fork and push a branch? I can take a quick look to see if I see any issues that might be causing the height / width to be off.

> Q: Is there a way to rotate the image 90°? For example if I want to use the screen horizontally?

Yes, we will have to extend the logic in `image.js` to rotate the image. I can take a look at providing an option to flip the orientation on my display.

**Comment by RaedsLab** [comment]
@samsonmking thanks ! You can find the draft PR here https://github.com/samsonmking/epaper.js/pull/9

**Comment by samsonmking** [comment]
At a first glance, everything looks OK to me. Can you add a console log after `image.js:11` to verify the height and width are getting set correctly?
```
const height = png.getHeight();
const width = png.getWidth();
console.log(`[${height}, ${width}]`);
```

**Comment by samsonmking** [comment]
@RaedsLab are you still interested in support for the 2in7 display? If you could help test, I could finish up the work you started in your PR back in August.

**Comment by samsonmking** [comment]
Closing for now, can reopen later if there is interest
