### ISSUE TITLE
Can't access Discord server

### ISSUE THREAD

**Issue by Mentor1337** [samsonmking/epaper.js#38]
I was working on a  few things and ran into a snag, I wanted to ask a few questions but when I clicked the Discord link (https://discord.com/channels/888893320309379122) and it says "no text channels" I think it may be because this is a link to the Discord channel rather than a sever invite.

**Comment by samsonmking** [comment]
@Mentor1337 good catch. I've updated the link, let me know if you still have trouble accessing it.
