### ISSUE TITLE
Working with PDF.js for larger e-ink reader displays

### ISSUE THREAD

**Issue by Utopiah** [samsonmking/epaper.js#4]
Hi, great project that I just noticed. Naive question : how do you imagine relying on https://github.com/mozilla/pdf.js could work?

I have a reMarkable (v1) that I rely enjoy on its own but it also have some extensibility potential... year relations locked down by a vendor https://github.com/remarkable which doesn’t interact much with an otherwise very active community https://github.com/reHackable/awesome-reMarkable .

Consequently I’m looking at DIY alternatives. Any suggestion?

**Comment by samsonmking** [comment]
A DIY PDF reader was actually my original inspiration for this project. I started with the smaller displays, as an inexpensive way to vet the idea. Waveshare sells a [9.7" display](https://www.waveshare.com/product/displays/e-paper/epaper-1/9.7inch-e-paper-hat.htm) with a refresh time that's listed as < 1 second. I think this display, a Raspberry Pi Zero, and a big usb battery could make a easy to build, large format, DIY ereader.
