### ISSUE TITLE
Build is broken in version 1.7.0

### ISSUE THREAD

**Issue by eshaham** [samsonmking/epaper.js#40]
I believe version 1.7.0 has broken the build.
After npm installing, running my app produces the following error:
```
Error: Could not locate the bindings file
```
Downgrading to version 1.6.0 solves the issue.

Running on RPi Zero, Node v14.4.0 via nvm

**Comment by schoes** [comment]
yes i found that bug too

**Comment by schoes** [comment]
but i can't find the source of the bug can anyone find it ?

**Comment by samsonmking** [comment]
I believe it may be caused by the some dependency upgrades in the last release. I'm going to try reverting the `package.json` to the last version and see if that fixes it.

**Comment by samsonmking** [comment]
Looks like it was just a typo in one of the imports in `devices.js`. A mistake I've made myself, too :slightly_smiling_face:.  @eshaham / @schoes let me know if you have any more problems.

**Comment by schoes** [comment]
the driver works now but now the display shows the Chare Right to left and not left to Right on my 2.7 inch epaper screen

**Comment by samsonmking** [comment]
@schoes can you open a new issue with the problem you're seeing? I don't own  a 2.7 inch display myself, so if you could attach some images, that'd help me get a better idea of what's going on.
