### ISSUE TITLE
Text is displayed RTL not LTR

### ISSUE THREAD

**Issue by schoes** [samsonmking/epaper.js#42]
When i use my 2.7 inch waveshare screen and render an index.html the text is displayed RTL and not LTR.
![IMG_0009](https://user-images.githubusercontent.com/3438263/141741946-b0fdd4fb-d3f7-4396-ac2e-7eab979b5a5b.jpg)
Version of lib 1.7.1
Display : waveshare 2.7 inch

**Comment by schoes** [comment]
index.html: 
`<!DOCTYPE html>
<html lang='en'>

<body>
    <h1 style="color: black;">Hello paper</h1>
</body>

<script src="webserver.js"></script>

</html>`

**Comment by schoes** [comment]
webserver.js script contnent:
`    // connect to the WebSocket API
    const ws = new WebSocket('ws://localhost:9090');
    ws.addEventListener('open', () => {
        // draw contents of DOM onto ePaper display
        ws.send('render');
    });`

**Comment by schoes** [comment]
index.js content: `const  {devices,init} = require( 'epaperjs');

init(devices.waveshare2in7, {
    webPort: 3000, // WebServer Port
    websocketPort: 9090, // WebSocket API Port
    staticDirectory: 'static', // Directory to serve frontend from
    skipWebServer: false, // If set to true will not create a local web server
});




`

**Comment by samsonmking** [comment]
@schoes thanks for the info! I think I've found a fix. Would you be able to pull this PR (#43) and help me test it?

**Comment by schoes** [comment]
fixerd with versiuon 1.7.2
