### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [samsonmking/epaper.js#5]
If you want I can write a [TypeScript type declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by samsonmking** [comment]
Thanks for the offer! Personally, I consider Typescript a must-have for bigger codebases, but this library is pretty small. I originally experimented with developing the whole thing in Typescript, but the build times were pretty slow on my Raspberry Pi B+. I think there's a good chance there may be some API churn as we work to bring in support for other devices and color modes. I think I'd like to hold off for now, and then potentially revisit once the API has gone through a few revisions.

**Comment by geopic** [comment]
Ok, no problem. Thanks for responding :+1:
