### ISSUE TITLE
value should be a variable?

### ISSUE THREAD

**Issue by JohnMcLear** [samsonmking/epaper.js#6]
https://github.com/samsonmking/epaper.js/blob/81f098a0b2d9338a5381048e7e03ff6b83961c2b/examples/weather-station/static/index.html#L140

**Comment by samsonmking** [comment]
Right now, my vision for epaper.js is to be a library that developers can use to build their own displays and applications.

In my opinion, this example is so simple that people can just change it directly to suite their needs. There's other things that might need to be customized, too, like units and country.

Do you think there would be interest in off the shelf apps you could install? For instance you could imagine doing something like `ngx epaperjs-weather --country=us --zip=12345`

**Comment by JohnMcLear** [comment]
@samsonmking I was just grazing the project and spotted what I would class as questionable coding practices.  I'm not a user :)

**Comment by samsonmking** [comment]
I will close for now, but thanks for the input :)
