### ISSUE TITLE
Npm install hangs

### ISSUE THREAD

**Issue by abhayakulkarni** [samsonmking/epaper.js#63]
Hello,
I am trying to install the library, for some reason the npm install -global hangs after loading for a while.
This is for 2.13 inch e paper HAT display

**Comment by samsonmking** [comment]
Hi @abhayakulkarni, sorry to hear you had trouble installing the library. ePaper.js uses `c` and `c++`  extensions to communicate with the displays. When you run `npm install` these extensions are compiled, which can take some time, especially on slower hardware, like the zero. If you wait a couple of minutes, the installation will usually complete. If it doesn't could you provide me with the following info:
- what version of node are you using and how did you install it (nvm, apt-get, etc)
- what's the exact command you're using to install ePaper.js?
- could you re-run the command with `--loglevel verbose`. So for example `npm i -g --loglevel verbose @epaperjs/core @epaperjs/2in13v2` and send me the output?

**Comment by abhayakulkarni** [comment]
Hello @samsonmking 
Thank you for your suggestion. The npm install worked perfectly fine now. Turns out it was an issue with the Wifi connectivity.
