### ISSUE TITLE
should hostname be hardcoded or a variable?

### ISSUE THREAD

**Issue by JohnMcLear** [samsonmking/epaper.js#7]
https://github.com/samsonmking/epaper.js/blob/81f098a0b2d9338a5381048e7e03ff6b83961c2b/examples/weather-station/static/index.html#L129

**Comment by samsonmking** [comment]
Good question. A few people have pointed out that this will not work if you've changed the Raspberry Pi's default hostname. I think I'll change it back to localhost, for now.

**Comment by samsonmking** [comment]
I have changed the hostname to localhost in both examples and will close this issue.
