### ISSUE TITLE
Not running on RPI4 64-bit (Please make JETSON !!!!!!!!!!)

### ISSUE THREAD

**Issue by Yonben** [samsonmking/epaper.js#71]
Hi,
I've been trying to run epaper.js on my Rpi4 and getting some issues. After installing everything I run the following command:
`ejs display rpi-7in5-v2 "https://github.com/samsonmking/epaper.js"`

And getting the following error (I ran with `--debug`):
```
Connecting to rpi-7in5-v2 screen
/***********************************/
Current environment: Debian
Please make JETSON !!!!!!!!!!
Connected
Displaying https://github.com/samsonmking/epaper.js
[DEBUG] Browser console.warning Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'. [ { url: undefined, lineNumber: undefined } ]
^CPowering off display and exiting...
Powering off display and exiting...
Failed to close SPI device.
: Bad file descriptor
```

Note that I'm using Raspbian 64-bit and not 32.
Obviously I saw `Please make JETSON !!!!!!!!!!` but Google didn't help much with that :/.

Any help would be appreciated.

Thanks a lot!

**Comment by samsonmking** [comment]
@Yonben apologies for the long delay on this fix. Raspberry Pi OS Bullseye 64bit is now officially supported! Please let me know if you have any issues
